version: '3'

services:
  mqx:
    image: bitnami/rabbitmq:3.11.18-debian-11-r0
    container_name: mqx-ctn
    ports:
      - "15672:15672"   # 管理界面
      - "5672:5672"     # AMQP
      - "25672:25672"   # 集群端口
      - "4369:4369"     # 用于节点发现
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=123456
      - RABBITMQ_VHOST=/
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_auth_backend_ldap, rabbitmq_delayed_message_exchange
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez
